import 'package:kureta_app/models/article.dart';

List<Article> articleMocks = [
  Article(
    title: "Some Title 1",
    excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
    imageUrl: "https://placeimg.com/640/480/any",
    category: "Technology",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  ),
  Article(
      title: "Some Title 2",
      excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
      imageUrl: "https://placeimg.com/640/480/any",
      category: "Traveling",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  ),
  Article(
      title: "Some Title 3",
      excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
      imageUrl: "https://placeimg.com/640/480/any",
      category: "Technology",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  )
];
List<Article> articleMocks2 = [
  Article(
      title: "Some Title 1",
      excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
      imageUrl: "https://placeimg.com/640/480/any",
      category: "Technology",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  ),
  Article(
      title: "Some Title 2",
      excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
      imageUrl: "https://placeimg.com/640/480/any",
      category: "Traveling",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  ),
  Article(
      title: "Some Title 3",
      excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
      imageUrl: "https://placeimg.com/640/480/any",
      category: "Technology",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  ),
  Article(
      title: "Some Title 4",
      excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
      imageUrl: "https://placeimg.com/640/480/any",
      category: "Traveling",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  ),
  Article(
      title: "Some Title 5",
      excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
      imageUrl: "https://placeimg.com/640/480/any",
      category: "Traveling",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  ),
  Article(
      title: "Some Title 6",
      excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse congue lectus non tellus tincidunt, bibendum convallis lorem mattis.",
      imageUrl: "https://placeimg.com/640/480/any",
      category: "Technology",
      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu nulla finibus, dignissim urna ut, volutpat quam. Phasellus efficitur pulvinar ligula et sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum vulputate vulputate leo, nec gravida mauris volutpat vel. Ut sit amet lorem eu tortor suscipit tempus. Aenean fermentum leo massa, a rutrum massa laoreet gravida. Sed nec porttitor diam, vel ornare dolor. Aliquam semper ultricies sapien, pulvinar vestibulum est volutpat quis. Praesent sit amet felis vehicula, condimentum urna a, lobortis lorem. In ipsum nisi, tincidunt cursus nibh sit amet, pellentesque ultricies purus. Nullam eleifend maximus arcu ut pretium. Suspendisse vulputate justo porttitor mi tincidunt, vel laoreet diam tempor. Etiam molestie lectus quam. Aliquam venenatis dui id sapien tincidunt posuere vel sed dui. Quisque scelerisque imperdiet enim sollicitudin porttitor. Ut mi nibh, efficitur quis facilisis tincidunt, hendrerit ac sem.Curabitur fermentum rutrum purus. Duis sed fringilla libero. In volutpat urna nec volutpat mattis. Nunc sed massa quam. Morbi eget lorem diam. Phasellus gravida vestibulum nisi, ac vestibulum est interdum eget. Vestibulum bibendum, odio eleifend mollis consequat, est erat volutpat turpis, a viverra eros sem et justo. Aenean condimentum lobortis risus, in egestas nisl vehicula eu.Phasellus commodo massa vel leo lobortis, nec ultricies nisl blandit. Nam mollis diam sapien, vitae tempus dui ultricies vel. Maecenas eu lorem nec nisi hendrerit efficitur eu eu dolor. Vestibulum non nibh a augue bibendum consectetur ac vitae ante. Curabitur facilisis, turpis ac lobortis pharetra, metus ante auctor ligula, ac fermentum eros justo et sem. Cras molestie elementum mi, nec convallis turpis pulvinar eget. Suspendisse vestibulum, nibh in sollicitudin aliquam, erat est lacinia libero, non fringilla mauris tortor vitae ante. Pellentesque eu tortor vestibulum, volutpat turpis in, consectetur nulla. Nullam sit amet eleifend urna. Ut dignissim velit quis urna vestibulum fringilla."
  ),
];